name: TVision2 Nightly build
on:
  schedule:
    - cron:  '0 3 * * *'
jobs:
  build:
    env:
      BUILD_CONFIG: Release
      VERSION_SUFFIX: -preview${{ github.run_id }}
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use .NET Core SDK 
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
        source-url: https://nuget.pkg.github.com/eiximenis/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} 
    - name: dotnet build
      run: dotnet build tvision2.sln -c $BUILD_CONFIG 
    - name: dotnet pack [Tvision2 Console Driver]
      run: dotnet pack ./src/Tvision2.ConsoleDriver/Tvision2.ConsoleDriver.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [Tvision2 Console Driver All]
      run: dotnet pack ./src/Tvision2.ConsoleDriver.All/Tvision2.ConsoleDriver.All.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [Tvision2 Console Driver Linux]
      run: dotnet pack ./src/Tvision2.ConsoleDriver.Linux/Tvision2.ConsoleDriver.Linux.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [Tvision2 Console Driver Windows]
      run: dotnet pack ./src/Tvision2.ConsoleDriver.Linux/Tvision2.ConsoleDriver.Windows.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [TvControls]
      run: dotnet pack ./src/Tvision2.Controls/Tvision2.Controls.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [TvControls Styles Mc]
      run: dotnet pack ./src/Tvision2.Controls.Styles.Mc/Tvision2.Controls.Styles.Mc.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [TVision2 Core]
      run: dotnet pack ./src/Tvision2.Core/Tvision2.Core.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [TVision2 Debug]
      run: dotnet pack ./src/Tvision2.Debug/Tvision2.Debug.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [TvDialogs]
      run: dotnet pack ./src/Tvision2.Dialogs/Tvision2.Dialogs.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [TvLayouts]
      run: dotnet pack ./src/Tvision2.Layouts/Tvision2.Layouts.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [TvStatex]
      run: dotnet pack ./src/Tvision2.Statex/Tvision2.Statex.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [TvStatex Controls]
      run: dotnet pack ./src/Tvision2.Statex.Controls/Tvision2.Statex.Controls.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [TVision2 Styles]
      run: dotnet pack ./src/Tvision2.Styles/Tvision2.Styles.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: dotnet pack [TVision2 Viewports]
      run: dotnet pack ./src/Tvision2.Viewports/Tvision2.Viewports.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix $VERSION_SUFFIX --no-build --include-source --include-symbols
    - name: Publish on Github Packages
      run: dotnet nuget push  '*.nupkg'  --skip-duplicate 
      working-directory: artifacts
